--Избор на база данни
USE [TestBase]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO
--Ако обектът съществува, то той да бъде изтрит
IF OBJECT_ID(N'[19118133].[V_CLIENTS_WITH_ACTIVE_CREDITS]', N'V') IS NOT NULL
BEGIN
 drop view [19118133].[V_CLIENTS_WITH_ACTIVE_CREDITS]
END
GO

--Създаване на обекта
CREATE VIEW [19118133].[V_CLIENTS_WITH_ACTIVE_CREDITS] 
AS 
SELECT C.CLIENT_EGN AS CL_EGN,
	   C.CLIENT_NAME AS CL_NAME,
	   C.CLIENT_SURNAME AS CL_SURNAME,
	   C.CLIENT_LASTNAME AS CL_LASTNAME,
	   COUNT(*) AS CREDIT_COUNT_A
FROM DATA.CLIENT C INNER JOIN DATA.CREDIT CR ON C.CLIENT_ID = CR.CLIENT_ID
WHERE STATUS_CODE = 'A'
GROUP BY CLIENT_EGN,CLIENT_NAME,CLIENT_SURNAME,CLIENT_LASTNAME