USE TestBase
GO 

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

--Ако обектът съществува, то той да бъде изтрит
IF OBJECT_ID(N'[19118133].[V_CLIENTS_WITH_OVERDUE_CREDITS]', N'V') IS NOT NULL
BEGIN
 drop view [19118133].[V_CLIENTS_WITH_OVERDUE_CREDITS]
END
GO
--Създаване на обекта
CREATE VIEW [19118133].[V_CLIENTS_WITH_OVERDUE_CREDITS]
AS 
SELECT CLIENT_EGN AS CL_EGN,
		CLIENT_NAME AS CL_NAME,
		CLIENT_SURNAME AS CL_SURNAME,
		CLIENT_LASTNAME AS CL_LASTNAME,
		(SELECT COUNT(*)
		FROM DATA.CREDIT 
		WHERE DATA.CREDIT.CLIENT_ID = C.CLIENT_ID AND STATUS_CODE = 'O'
		)AS CREDIT_COUNT_O,
		ADDRESS_TOWN AS TOWN,	
		ADDRESS_PCODE AS [ZIP CODE],
		ADDRESS_TEXT AS ADDRESS
FROM DATA.CLIENT C --INNER JOIN DATA.CREDIT CR ON C.CLIENT_ID = CR.CLIENT_ID
					LEFT JOIN DATA.CLIENT_ADDRESS CA ON CA.CLIENT_ID = C.CLIENT_ID AND ADDRESS_TYPE = 'K'
WHERE EXISTS (SELECT *
				FROM DATA.CREDIT
				WHERE STATUS_CODE = 'O' AND DATA.CREDIT.CLIENT_ID = C.CLIENT_ID) 
GROUP BY C.CLIENT_ID,CLIENT_EGN,CLIENT_NAME,CLIENT_SURNAME,CLIENT_LASTNAME,ADDRESS_TYPE,ADDRESS_TOWN,ADDRESS_PCODE,ADDRESS_TEXT,CA.CLIENT_ID
			

	

